### ISSUE TITLE
TypeError in the semantic check of primitive_action

### ISSUE THREAD

**Issue by pschuprikov** [p4lang/p4-hlir#17]
In [this](https://github.com/p4lang/p4-hlir/blob/master/p4_hlir/frontend/ast.py#L345) line of code the argument types of **primitive_action** are set to `P4NamedObject`. Later on [here](https://github.com/p4lang/p4-hlir/blob/master/p4_hlir/frontend/semantic_check.py#L395) this `P4NamedObject` is being &-ed with a `set`, which is constructed, probably, [here](https://github.com/p4lang/p4-hlir/blob/master/p4_hlir/frontend/semantic_check.py#L246), resulting in ```TypeError```.

The issue appeared when I tried to use a primitive action `foo`, which was defined in p4 program by:
```
primitive_action foo(a, b);
```

**Comment by antoninbas** [comment]
Hi Pavel,
Declaring action primitives in your P4 program using the `primitive_action` construct is virtually useless at this point. We quickly realized that this declaration did not carry enough information to be useful to the compiler, which is why we currently rely on JSON files to declare primitives (e.g. https://github.com/p4lang/p4-hlir/blob/master/p4_hlir/frontend/primitives.json). I reached out to the spec maintainers to see if we can remove this part of the spec (beginning of section 9.1) which describes how action primitives can be declared. However, we believe that being able to declare action primitives within your P4 program is useful, which is why we are committed to fixing this feature in the future.

**Comment by pschuprikov** [comment]
Ok, I see. Thank you for directing me towards the JSON-based declaration.

I'm not sure whether I should close the issue or not since the problem does exist. But, personally, I don't have any further questions and I'm OK if it is closed.

**Comment by antoninbas** [comment]
Let's leave it open. I'll close it when the relevant text is updated in the P4 spec.

**Comment by antoninbas** [comment]
The P4_14 spec has been updated (1.0.3) to remove the ability to define new primitive actions in the P4 program itself: http://p4.org/wp-content/uploads/2016/11/p4-spec-latest.pdf
Instead, the burden is left to the compiler implementation to be able to absorb new target-specific primitives, which for this implementation is done through the JSON definitions.
Hopefully, a future version of the language will reintroduce this feature in a usable form.
