### ISSUE TITLE
Primitive action: meter or execute_meter?

### ISSUE THREAD

**Issue by ghost** [p4lang/p4-hlir#3]
The active P4 spec (1.0.2) defines the primitive action as meter (Table 4 and p41)

The HLIR parser (as well as sample code in P4Factory) uses execute_meter as the primitive action. 

Is there a change pending in the spec or does the code here (and examples) need to migrate to 'meter'?

**Comment by antoninbas** [comment]
Our P4 parser assumes that 'meter' is actually a keyword in the language, which collided with the action primitive name
We decided to change the primitive name to 'execute_meter' to avoid this issue
To be honest a better parser (i.e. a parser which does not assume that 'meter' is a keyword) would not have required this change. Which is why we are not sure yet about whether to update the spec or write a better parser for the compiler.
